# DIRECT EasyPIM Pipeline - NO VALIDATION STAGE BLOCKING
# This will actually run the EasyPIM script!

trigger: none

parameters:
- name: keyVaultName
  displayName: 'Key Vault Name'
  type: string
  default: 'kv-easypim-8368'
- name: configSecretName
  displayName: 'Configuration Secret Name'  
  type: string
  default: 'easypim-config-json'

pool: Default

variables:
- group: EasyPIM-EventDriven-Governance

jobs:
- job: DirectEasyPIMExecution
  displayName: 'Direct EasyPIM Execution'
  timeoutInMinutes: 10
  steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: 'RUN EASYPIM NOW'
    inputs:
      azureSubscription: 'EasyPIM-Azure-Connection'
      scriptType: 'inlineScript'
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
      failOnStandardError: false
      inlineScript: |
        Write-Host "🚀 STARTING EASYPIM EXECUTION - NO VALIDATION BLOCKING!" -ForegroundColor Red
        Write-Host "📋 Key Vault: ${{ parameters.keyVaultName }}" -ForegroundColor Yellow
        Write-Host "📋 Secret: ${{ parameters.configSecretName }}" -ForegroundColor Yellow
        
        # Install EasyPIM module
        Write-Host "📦 Installing EasyPIM module..." -ForegroundColor Green
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -Force
        Install-Module -Name EasyPIM.Orchestrator -Force -Scope CurrentUser -AllowClobber -Verbose
        
        # Import module  
        Import-Module EasyPIM.Orchestrator -Force -Verbose
        
        # Verify command exists
        $cmd = Get-Command -Name "Invoke-EasyPIMOrchestrator" -ErrorAction SilentlyContinue
        if ($cmd) {
          Write-Host "✅ EasyPIM command found!" -ForegroundColor Green
        } else {
          Write-Host "❌ EasyPIM command NOT found!" -ForegroundColor Red
          Get-Module -ListAvailable | Where-Object Name -like "*EasyPIM*" | Format-Table
          throw "EasyPIM module not available"
        }
        
        # Get Graph token via Azure CLI
        Write-Host "🔐 Getting Microsoft Graph token..." -ForegroundColor Cyan
        try {
          $graphToken = az account get-access-token --resource https://graph.microsoft.com --query "accessToken" -o tsv
          if ($graphToken -and $graphToken.Length -gt 50) {
            Write-Host "✅ Graph token acquired (length: $($graphToken.Length))" -ForegroundColor Green
            
            # Connect to Graph
            Import-Module Microsoft.Graph.Authentication -Force -ErrorAction SilentlyContinue
            $secureToken = ConvertTo-SecureString $graphToken -AsPlainText -Force
            Connect-MgGraph -AccessToken $secureToken -NoWelcome
            Write-Host "✅ Connected to Microsoft Graph" -ForegroundColor Green
          }
        } catch {
          Write-Host "⚠️ Graph connection failed: $_" -ForegroundColor Yellow
        }
        
        # EXECUTE EASYPIM NOW!
        Write-Host "🎯 EXECUTING EASYPIM ORCHESTRATOR NOW!" -ForegroundColor Red
        try {
          Invoke-EasyPIMOrchestrator -KeyVaultName '${{ parameters.keyVaultName }}' -SecretName '${{ parameters.configSecretName }}' -WhatIf:$false -Mode 'delta' -Verbose
          Write-Host "✅ EASYPIM EXECUTION COMPLETED!" -ForegroundColor Green
        } catch {
          Write-Host "❌ EASYPIM EXECUTION FAILED: $_" -ForegroundColor Red
          Write-Host "Error details: $($_.Exception.Message)" -ForegroundColor Red
          Write-Host "Stack trace: $($_.ScriptStackTrace)" -ForegroundColor Red
          # Don't throw - let's see what happened
        }
        
        Write-Host "🏁 Script completed" -ForegroundColor Magenta
