# Simple Authentication Test Pipeline
# This tests the exact same authentication as the main orchestrator

trigger: none

parameters:
- name: serviceConnection
  displayName: 'Azure Service Connection'
  type: string
  default: 'EasyPIM-Azure-Connection'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: EasyPIM-EventDriven-Governance

jobs:
- job: AuthTest
  displayName: 'Authentication Test'
  steps:
  - checkout: none
    displayName: 'Skip Checkout'

  - task: AzurePowerShell@5
    displayName: 'Test Azure PowerShell Authentication'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'inlineScript'
      azurePowerShellVersion: 'LatestVersion'
      script: |
        Write-Host "Testing Azure PowerShell authentication..."
        $context = Get-AzContext
        Write-Host "Current Azure Context:"
        Write-Host "Account: $($context.Account.Id)"
        Write-Host "Subscription: $($context.Subscription.Name)"
        Write-Host "Tenant: $($context.Tenant.Id)"
        
        Write-Host "Testing Key Vault access..."
        try {
          $vault = Get-AzKeyVault -VaultName "$(AZURE_KEY_VAULT_NAME)"
          Write-Host "✅ Key Vault access successful: $($vault.VaultName)"
        } catch {
          Write-Host "❌ Key Vault access failed: $($_.Exception.Message)"
          Write-Host "Key Vault Name: $(AZURE_KEY_VAULT_NAME)"
        }

  - task: AzureCLI@2
    displayName: 'Test Azure CLI Authentication'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Testing Azure CLI authentication..."
        az account show
        
        echo "Testing Key Vault access..."
        az keyvault show --name $(AZURE_KEY_VAULT_NAME) || echo "Key Vault access failed"
        
        echo "Testing Graph API access..."
        az ad app list --display-name "EasyPIM" --query "[].{appId:appId,displayName:displayName}" || echo "Graph API access failed"
